/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2022-06-27 08:48:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.utils.common.CmmnUtil;
import common.utils.common.PentasMap;
import common.utils.string.StringUtil;
import common.config.properties.SettingProperties;
import java.util.List;
import common.utils.json.JsonUtil;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/common/include/home_static_resource.jsp", Long.valueOf(1656316069244L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/common_header.jsp", Long.valueOf(1656310740464L));
    _jspx_dependants.put("/WEB-INF/jsp/common/include/home_header.jsp", Long.valueOf(1656319720090L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("common.utils.common.CmmnUtil");
    _jspx_imports_classes.add("common.utils.string.StringUtil");
    _jspx_imports_classes.add("common.config.properties.SettingProperties");
    _jspx_imports_classes.add("common.utils.common.PentasMap");
    _jspx_imports_classes.add("common.utils.json.JsonUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	SettingProperties settingProperties = (SettingProperties)CmmnUtil.getBean("settingProperties");
	String rscVer = settingProperties.getRscVer();

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t<title>중고거래</title>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- <meta name=\"format-detection\" content=\"telephone=no\"> -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/static_resources/home/image/common/favicon.png\">\r\n");
      out.write("\r\n");
      out.write("<!-- css [s] -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/reset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/set.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/layout.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/common.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/swiper.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/swiper-bundle.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/fittingRoom.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/static_resources/home/css/header.css\">\r\n");
      out.write("<!-- css [e] -->\r\n");
      out.write("\r\n");
      out.write("<!-- css [e] -->\r\n");
      out.write("\r\n");
      out.write("<!-- js [s] -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/static_resources/home/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/static_resources/home/js/swiper.min.js\"></script>\r\n");
      out.write("<!-- <script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/common_js.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/ion.rangeSlider.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/jquery.modal.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/jquery-migrate-1.2.1.min.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/jquery-ui.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/mcxdialog_ui.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("<script type=\"text/javascript\" src=\"/static_resources/home/js/ux/gaga.validation.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/static_resources/home/js/ux/wishlist.js\"></script> -->\r\n");
      out.write("<!-- js [e]  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/static_resources/js/common.js?rscVer=");
      out.print(rscVer);
      out.write("\"></script>\r\n");
      out.write("<script src=\"/static_resources/lib/axios/0.21.0/axios.min.js\"></script>\r\n");
      out.write("<script src=\"/static_resources/lib/CryptoJS/3.1.2/rollups/sha256.js\"></script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write('\r');
      out.write('\n');

	String loginStat = StringUtil.defaultString((String) request.getAttribute("loginStat"), "");
	String MBR_ID = StringUtil.defaultString((String) session.getAttribute("MBR_ID")); // 사용자 ID

      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t <div class=\"header-div\" style=\"display:  flex;\">\r\n");
      out.write("\t \r\n");
      out.write("\t <div class=\"left-content\">\r\n");
      out.write("          <ul class=\"MainUl\">\r\n");
      out.write("       \t\t<li id=\"heaher-logo\"><Link to=\"/\"><img src=\"static_resources/img/logo.png\" alt=\"\"></img></Link></li>\r\n");
      out.write("            <li id=\"menu-li\"><a href=\"javascript:void(0)\" class=\"Header-Menu\">🛒마켓</a></li>\r\n");
      out.write("            <li id=\"menu-li\"><a href=\"javascript:void(0)\" class=\"Header-Menu\">👨‍👨왁자지껄</a></li>\r\n");
      out.write("            <li id=\"menu-li\"><a href=\"javascript:void(0)\" class=\"Header-Menu\">❕❔질문</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\t </div>\r\n");
      out.write("     <div class=\"right-content\">\r\n");
      out.write("\t\t\t<span class='offLogin' style=\"display:none\"><a href=\"javascript:void(0);\" onclick=\"goLoginPop()\"\ttitle=\"로그인 바로가기\">로그인</a></span> \r\n");
      out.write("\t\t\t<span class='offLogin' style=\"display:none\"><a href=\"javascript:void(0);\" onclick=\"goJoinPop()\" title=\"회원가입 바로가기\">회원가입</a></span>\r\n");
      out.write("\t\t\t<span class='onLogin' style=\"display:none\">환영합니다. ");
      out.print(MBR_ID);
      out.write(" 님</span>\r\n");
      out.write("\t\t\t<span class='onLogin' style=\"display:none\"><a href=\"javascript:void(0);\" onclick=\"goShowRoom()\" title=\"마이페이지 바로가기\">마이룸</a></span>\r\n");
      out.write("\t\t\t<span class='onLogin' style=\"display:none\"><a href=\"/logoutProc\" >로그아웃</a></span>\r\n");
      out.write("\t </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("<!-- 로그인 팝업 [s] -->\r\n");
      out.write("<div class=\"layerPrivacy\">\r\n");
      out.write("\t<div class=\"bg\"></div>\r\n");
      out.write("\t<div class=\"popupcont\">\r\n");
      out.write("\t\t<div class=\"popupBody\">\r\n");
      out.write("\t\t\t<div class=\"btn_close\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\">close</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content login\">\r\n");
      out.write("\t\t\t\t<!-- 페이지특정 클래스 = login -->\r\n");
      out.write("\t\t\t\t<div class=\"cont_head\">\r\n");
      out.write("\t\t\t\t\t<h4>로그인</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cont_body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form_wrap form_col_c form_full\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"_csrf\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form_field\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input_label sr-only\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"mbrId\" id=\"mbrId\" placeholder=\"아이디\" class=\"form_control\" onkeyup=\"if( event.keyCode==13 ){ $('#mbrPw').focus();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form_field mt10\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input_label sr-only\">비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"mbrPw\" id=\"mbrPw\" class=\"form_control\" placeholder=\"비밀번호\" onkeyup=\"if( event.keyCode==13 ){ goLogin();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_row mt40\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn_dark btn_block\" onclick=\"goLogin()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>로그인</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 로그인 팝업 [e] -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 회원가입 팝업 [s] -->\r\n");
      out.write("<div class=\"layerPrivacy_poly\">\r\n");
      out.write("\t<div class=\"bg\"></div>\r\n");
      out.write("\t<div class=\"popupcont\">\r\n");
      out.write("\t\t<div class=\"popupBody\">\r\n");
      out.write("\t\t\t<div class=\"btn_close\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\">close</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content login\">\r\n");
      out.write("\t\t\t\t<div class=\"cont_head\">\r\n");
      out.write("\t\t\t\t\t<h4>회원가입</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"cont_body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"form_wrap form_col_c form_full\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"_csrf\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form_field\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input_label sr-only\">아이디</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"joinId\" id=\"joinId\" placeholder=\"아이디\" class=\"form_control\" onkeyup=\"if( event.keyCode==13 ){ $('#joinPw').focus();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 비밀번호 [s] -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form_field mt10\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input_label sr-only\">비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"joinPw\" id=\"joinPw\" class=\"form_control\" placeholder=\"비밀번호\" onkeyup=\"if( event.keyCode==13 ){ $('#joinPwChk').focus();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 비밀번호 [e] -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 비밀번호 확인 [s] -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form_field mt10\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"input_label sr-only\">비밀번호 확인</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input_wrap\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"joinPwChk\" id=\"joinPwChk\" class=\"form_control\" placeholder=\"비밀번호 화인\" onkeyup=\"if( event.keyCode==13 ){ joinMbr();}\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- 비밀번호 확인 [e] -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"ui_row mt40\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"ui_col_12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn_dark btn_block\" onclick=\"joinMbr()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>회원가입</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 회원가입 팝업 [e] -->\r\n");
      out.write("<script>\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$('.layerPrivacy .btn_close, .layerPrivacy .bg').click(function() {\r\n");
      out.write("\t\t$('.layerPrivacy').removeClass('on');\r\n");
      out.write("\t});\r\n");
      out.write("\t$('.layerPrivacy_poly .btn_close, .layerPrivacy_poly .bg').click(function() {\r\n");
      out.write("\t\t$('.layerPrivacy_poly').removeClass('on');\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar loginStat = \"");
      out.print(loginStat);
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\tif(loginStat === \"LOGIN_FAIL\"){\r\n");
      out.write("\t\talert(\"로그인 정보를 확인하세요.\")\r\n");
      out.write("\t}\r\n");
      out.write("\tif( \"");
      out.print(MBR_ID);
      out.write("\" == \"\" || \"");
      out.print(MBR_ID);
      out.write("\" == undefined){\r\n");
      out.write("\t\t$(\".offLogin\").show();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\".onLogin\").show();\r\n");
      out.write("\t}\r\n");
      out.write("})\t\r\n");
      out.write("\t\r\n");
      out.write("function goLoginPop() {\r\n");
      out.write("\t$(\"#mbrId\").val('');\r\n");
      out.write("\t$(\"#mbrPw\").val('');\r\n");
      out.write("\t$(\".layerPrivacy\").addClass('on');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goJoinPop() {\r\n");
      out.write("\t$(\"joinId\").val('');\r\n");
      out.write("\t$(\"joinPw\").val('');\r\n");
      out.write("\t$(\"#joinPwChk\").val('');\r\n");
      out.write("\t$('.layerPrivacy_poly').addClass('on');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validateJoin(){\r\n");
      out.write("\t\r\n");
      out.write("\tif(cf_isEmpty($(\"#joinId\").val().trim())){\r\n");
      out.write("\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#joinId\").focus();  return false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(cf_isEmpty($(\"#joinPw\").val().trim())){\r\n");
      out.write("\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t$(\"#joinPw\").focus();  return false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif($(\"#joinPw\").val() != $(\"#joinPwChk\").val()){\r\n");
      out.write("\t\talert(\"비밀번호를 확인해주세요.\")\r\n");
      out.write("\t\t$(\"#joinPwChk\").focus(); return false;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function joinMbr() {\r\n");
      out.write("\tif(!valideJoin())\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t\r\n");
      out.write("\tparams = {\r\n");
      out.write("\t\tmbrId : $('#joinId').val(),\r\n");
      out.write("\t\tmbrPw : CryptoJS.SHA256($(\"#joinPw\").val().toString())\r\n");
      out.write("\t}\r\n");
      out.write("\tcf_call(\"/joinMbr\", params, joinMbrCB);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function joinMbrCB(data) {\r\n");
      out.write("\tif(data.result == \"succ\"){\r\n");
      out.write("\t\talert(\"회원가입이 완료됐습니다.\");\r\n");
      out.write("\t\tlocation.href=\"/\"\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"이미 사용 중인 아이디 입니다.\")\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function goLogin() {\r\n");
      out.write("\t\r\n");
      out.write("\tif(!validataLogin()) return;\r\n");
      out.write("\t\r\n");
      out.write("\tvar params = {\r\n");
      out.write("\t\t\tmbrIf : $(\"mbrId\").val(),\r\n");
      out.write("\t\t\tinputMbrPw : CryptoJS.SHA256($(\"#mbrPw\").val()).toString(),\r\n");
      out.write("\t\t}\r\n");
      out.write("\tcf_gotoUrl(\"/loginProc\", params);\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function goMyPage() {\r\n");
      out.write("\tlocation.href=\"/myPage\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function isLogin(){\r\n");
      out.write("\tif(\"");
      out.print(MBR_ID);
      out.write("\" == \"\" || \"");
      out.print(MBR_ID);
      out.write("\" == null || \"");
      out.print(MBR_ID);
      out.write("\" == undefined){\r\n");
      out.write("\t\talert(\"로그인후 이용 가능합니다.\")\t\t\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
